# Spring properties
spring:
  application:
    name: airlines-service
# HTTP Server
server:
  port: 8098
# Eureka Server Access
eureka-server:
  enabled: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
