spring:
  application:
    name: airlines-service
server:
  port: 8098
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://127.0.01:8761/eureka/