spring:
  application:
    name: airlines-service
server:
  port: 8098
eureka-server:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/