spring:
  application:
    name: airlines-service
server:
  port: 8098
eureka-server:
  instance:
    hostName: eureka-server
    preferIpAddress: false
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/