spring:
  profiles: default

server:
  port: ${PORT:8761}

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
---

spring:
  profiles: swarm
  cloud:
    inetutils:
      preferredNetworks:
        - app_network  

server:
  port: ${PORT:8761}

eureka:
  instance:
    hostname: eureka
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

---
spring:
  profiles: aws
server:
  port: 8761
  servlet:
    context-path: /eureka
eureka:
  environment: production
  instance:
    non-secure-port: ${server.port}
    hostname: eureka
  client:
region: eu-west-1
availabilityZones:
        eu-west-1: eu-west-1a,eu-west-1b,eu-west-1c
    registerWithEureka: false
    fetchRegistry: false
    eurekaServerDNSName: r53config.vpc
    eurekaServerPort: 8761
eurekaServerURLContext: /eureka/eureka
    useDnsForFetchingServiceUrls: true
