spring:
   profiles: default
server:
  port: 8074
  
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 20
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://eureka:eurekapass@${eureka.instance.hostname}:8761/eureka/eureka
ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 10000
  
hystrix:
    command:
        default:
            execution:
                isolation:
                  strategy: THREAD
                  thread:
                    timeoutInMilliseconds: 10000
                    
---

spring:
   profiles: k8s
server:
  port: 8074

ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 10000
  
hystrix:
    command:
        default:
            execution:
                isolation:
                  strategy: THREAD
                  thread:
                    timeoutInMilliseconds: 10000                       

---

spring:
  profiles: swarm
  cloud:
    inetutils:
      preferredNetworks:
        - app_network
server:
  port: 8074
eureka:
  instance:
    hostname: eureka
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 20

  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka:eurekapass@${eureka.instance.hostname}:8761/eureka/eureka

ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 10000
  
hystrix:
    command:
        default:
            execution:
                isolation:
                  strategy: THREAD
                  thread:
                    timeoutInMilliseconds: 10000

---

spring:
   profiles: aws
server:
  port: 8074
eureka:
  environment: production
  instance:
    non-secure-port: ${server.port}
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 20
  client:
    region: eu-west-1
    registerWithEureka: true
    fetchRegistry: true
    eurekaServerDNSName: r53config.vpc
    eurekaServerPort: 8761
    eurekaServerURLContext: /eureka/eureka
    useDnsForFetchingServiceUrls: true
ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 10000
  
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 10000    