server:
  port: 8098
 
spring:
  application:
    name: eureka-client
eureka:
  enabled: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
      port: ${PORT:8761}
