spring:
  application:
    name: airlines-service-client
  cloud:
    config:
      uri: http://config-services:8888
  freemarker:
    enabled: false 
  thymeleaf:
    cache: false
    prefix: classpath:/templates/