server:
  port: ${PORT:8761}
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  instance:
    hostname: eureka
    preferIpAddress: false
  server:
    waitTimeInMsWhenSyncEmpty: 0 