version: "3"
services:
  eureka-server:
    image: jmc22071983/eureka-server:0.0.1-SNAPSHOT
    ports:
      - 8761
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - app_network
    hostname: eureka
  airlines-service:
    image: jmc22071983/airlines-service:0.0.1-SNAPSHOT
    environment:
      - couchbase_addr=192.168.99.101:8091
    depends_on:
      - eureka-server
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - 8098
    networks:
      - app_network
    environment:
     eureka.client.serviceUrl.defaultZone: http://eureka:8761/eureka/

networks:
    app_network: