server:
  port: 8888
spring:
  profiles:
    active: git
  application:
    name: config
  cloud:
    config:
      server:
        prefix: /config
        git:
          uri: https://github.com/jmc22071983/config