server:
  port: 8888
spring:
  profiles:
    active: git
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jmc22071983/config
security:
  user:
    name: configUser
    password: configPassword
    role: SYSTEM
